cargo test
cat bindings/*.ts > bindings/types.svelte
sed -i '' 's/\/\/ This file was generated by \[ts-rs\](https:\/\/github.com\/Aleph-Alpha\/ts-rs)\. Do not edit this file manually\.//g'  bindings/types.svelte
sed -i ''  '/^[import]/d' bindings/types.svelte
sed '1 i\
<script lang="ts", context="module">' bindings/types.svelte | tee types.svelte
sed -i -e '$a\'$'\n''</script>' types.svelte
npx prettier --write --plugin prettier-plugin-svelte types.svelte

cp types.svelte ../src/types
