cargo test
cat bindings\*.ts > types1.ts

# have to use Out-File instead of >> (redirection) because file will be binary, not txt, prettier error
get-content .\types1.ts | %{$_ -replace "// This file was generated by \[ts-rs\]\(https://github.com/Aleph-Alpha/ts-rs\)\. Do not edit this file manually\.",""} | Out-File types2.ts -Encoding ASCII
get-content .\types2.ts | %{$_ -replace "(?<=import).*?(?=;)",""} | Out-File types3.ts -Encoding ASCII
get-content .\types3.ts | %{$_ -replace "import;",""} | Out-File types4.ts -Encoding ASCII


prettier --write types4.ts
cp types4.ts ..\src\types.ts

rm -r bindings
rm types*.ts
